# Generated by Django 5.2 on 2025-08-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscriptionplan_max_businesses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='api_access',
        ),
    ]
